"""added columns

Revision ID: 9ede7aa094d3
Revises: 371ab6e37bfc
Create Date: 2021-03-05 14:52:25.747133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ede7aa094d3'
down_revision = '371ab6e37bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('crust', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('delivery', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('flavor', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('no_of_pizzas', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('toppings', sa.String(length=255), nullable=True))
    op.drop_column('orders', 'category')
    op.drop_column('orders', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('orders', 'toppings')
    op.drop_column('orders', 'no_of_pizzas')
    op.drop_column('orders', 'flavor')
    op.drop_column('orders', 'email')
    op.drop_column('orders', 'delivery')
    op.drop_column('orders', 'crust')
    # ### end Alembic commands ###
