"""added columns

Revision ID: b5b20d5d473d
Revises: 1f1e2c7c249e
Create Date: 2021-03-05 16:41:32.968038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b20d5d473d'
down_revision = '1f1e2c7c249e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'pass_secure',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'pass_secure',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
